### ISSUE TITLE
Please support signTypedData_v4 on Trezor One

### ISSUE THREAD

**Issue by gruvin** [trezor/trezor-firmware#1680] opened 2021-06-24 10:11 UTC
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
Firmware support for signTypedData_v4 signing

**Describe alternatives you've considered**
Ditch Trezor in favor of a HW wallet that supports signTypedData_v4 ? Would rather seriously not. Already got a Ledger Nano and don't like it.

**Additional context**
Needed for 1inch.io exchange and a growing number of other sites.

**Comment by prusnak** [comment] 2021-06-24 11:23
Duplicate of https://github.com/trezor/trezor-firmware/issues/1272

**Closed by prusnak** 2021-06-24 11:23 UTC
Labels: enhancement, feature
