### ISSUE TITLE
T2B1 homescreen upload

### ISSUE THREAD

**Issue by Hannsek** [trezor/trezor-firmware#3019] opened 2023-05-17 07:39 UTC
I tried to upload 
![#2](https://github.com/trezor/trezor-firmware/assets/57008159/f1d93959-7059-4fa4-b72f-468d0fe86690)
onto the device.

I got this: 
![IMG_8410](https://github.com/trezor/trezor-firmware/assets/57008159/86d19b30-8617-4110-936b-4534b86d1146)

However: this ![jezek](https://github.com/trezor/trezor-firmware/assets/57008159/d2e967b0-c4a9-43e2-9cfa-6f5c9c89e8b1) went well. (Picture from https://trezor.github.io/homescreen-editor/)

**Comment by grdddj** [comment] 2023-05-29 13:09
The issue is in the uploaded image, it does not have `black(0,0,0)`, but `black(25,25,25)`, so it makes the "dotted" background. 

With a completely black/white image I had no issues (and I guess the hedgehog is also purely b/w)

Try this screenshot:

![image](https://github.com/trezor/trezor-firmware/assets/42543243/5d0cac0d-70e7-49dc-8ff6-108df93eab8a)

**Comment by Hannsek** [comment] 2023-05-29 13:20
Shouldn't  trezorlib convert it to black and white automatically?

**Comment by matejcik** [comment] 2023-05-29 13:27
how would trezorlib know which color to assign to black?

**Comment by grdddj** [comment] 2023-05-29 13:33
> Ok, how it is done [here](https://trezor.github.io/homescreen-editor/)?

Looks like the `brightness` option is controlling the threshold for black/white.

Something similar _could_ be easily done by `trezorlib`, but I do not think we want to do these things:

```python
def black_or_white(image_path, threshold=128) -> Image:
    # Open the image file
    image = Image.open(image_path)
    # Convert image to grayscale
    image = image.convert('L')
    # Apply the threshold
    return mage.point(lambda p: p > threshold and 255)
```

**Comment by matejcik** [comment] 2023-05-29 13:40
yeah, trezorctl is not an image editor.
why is it a problem to supply an image with the right colors?

**Closed** 2023-05-31 11:00 UTC
Labels: bug
