### ISSUE TITLE
2.3.1 RC1 doesn't boot up

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-firmware#1008] opened 2020-05-23 08:51 UTC
**Describe the bug**
RC1 of 2.3.1 doesn't boot up

**Firmware version or revision**
2.3.1 regular and 2.3.1 btc-only won't start 
tested on two devices 

**Desktop/smartphone setup (please complete the following information):**
nixOS

**To Reproduce**
1) load fw to device
2) confirm that it's not signed
3) see black screen

**Expected behavior**
device will boot up

**Screenshots**
https://photos.app.goo.gl/NTATmxRWP8twSgna6

**Additional context**

**Comment by tsusanka** [comment] 2020-05-23 09:44
@bosomt please always include the firmware revision. It is 2dc0107b correct?

**Comment by tsusanka** [comment] 2020-05-23 09:45
I am confirming this. The device is also not listed via `trezorctl list`.

**Comment by bosomt** [comment] 2020-05-23 09:50
sorry I forgot
that's correct

ls | grep 2.3.1
trezor-fw-btconly-2.3.1-2dc0107b.bin
trezor-fw-regular-2.3.1-2dc0107b.bin

**Comment by tsusanka** [comment] 2020-05-23 10:47
Happens on current master (675ff459) as well.

**Comment by tsusanka** [comment] 2020-05-23 10:48
Bumping priority in https://github.com/trezor/trezor-firmware/issues/946. This is exactly what we would have caught early if it would be implemented.

**Comment by tsusanka** [comment] 2020-05-23 11:13
I have bisected this to 0d65d684f0bb2d4c604c0a7822237b5095f74bd5. That is the first bad commit.

Maybe the TREZOR_MODEL variable is not properly set to "T"? I have tried to build with `TREZOR_MODEL=T make build_firmware` with no success though. I think `make build_firmware` still should build Trezor T firmware on default.

@hiviah could you look at this please? Of course on Monday is enough.

**Comment by hiviah** [comment] 2020-05-23 16:00
This was caused by weird gcc property where .s assembler files are not preprocessed and .S files are, so T1 code was getting mixed into TT code. Fix in pull request #1009 .

**Comment by prusnak** [comment] 2020-05-24 10:28
Closed via https://github.com/trezor/trezor-firmware/pull/1009

**Closed by prusnak** 2020-05-24 10:28 UTC
Labels: P1 Urgent, S1 Blocker, bug
