### ISSUE TITLE
los funds with MetaMask using avalanche chain with trezor

### ISSUE THREAD

**Issue by fili777** [trezor/trezor-firmware#1912] opened 2021-11-11 14:09 UTC
los funds with MetaMask using avalanche chain with trezor

I tried to scan to address with crypto and findeth

scanned also with ledger with the same seed and trezor in metamask

looks like the address disappeared from my seed. 

i didn't use any passphrase

**Comment by matejcik** [comment] 2021-11-11 14:11
Duplicate of #1910, which is a duplicate of #1850 

Please don't open more issues about the same thing.

**Closed by matejcik** 2021-11-11 14:11 UTC
Labels: bug
