### ISSUE TITLE
Receive address - Inconsistency between models in displaying derivation path

### ISSUE THREAD

**Issue by sorooris** [trezor/trezor-firmware#1735] opened 2021-07-27 12:53 UTC
**Describe the bug**
Model One does not display derivation path of a coin when showing receive address.

**Firmware version and revision**
Any (tested 2.4.1 24bb4016 and 1.10.2 24bb4016)

**Desktop setup:**
 - Wallet software: Trezor Wallet or Suite
 - OS: any (tested NixOS 21.05)
 - Browser: any (tested Chromium 91.0.4472.77)

**To Reproduce**
1. Connect model One to the computer,
2. Select Receive address of any coin in either Suite or Wallet,
3. Repeat steps above for model T,
4. Compare derivation paths on both screens.

**Expected behavior**
Both models display the derivation path of the selected coin.

**Actual behavior**
Only model T displays the derivation path.

**Screenshots**
Derivation path displayed on T | No derivation path on One
------------ | -------------
![image](https://user-images.githubusercontent.com/10185314/127155692-f340c129-4c81-4d10-82f6-ddca9a943e54.png) | ![image](https://user-images.githubusercontent.com/10185314/127155704-b4544198-d4b5-42b5-8bd4-f3828341803c.png)

**Comment by matejcik** [comment] 2022-12-13 14:38
essentially a duplicate of #2151 / #1244

**Closed by matejcik** 2022-12-13 14:38 UTC
Labels: feature
