### ISSUE TITLE
Allow for going back to previous word

### ISSUE THREAD

**Issue by grdddj** [trezor/trezor-firmware#3362] opened 2023-10-19 18:02 UTC
In backup, when I enter bad word,  I cannot  fix it after pressing enter. 

Applies for both models (TT, TR)

**Comment by Hannsek** [comment] 2023-10-19 21:27
Duplicate of [this](https://github.com/trezor/trezor-firmware/issues/286).

**Closed by Hannsek** 2023-10-19 21:27 UTC
