### ISSUE TITLE
Keyboard still get gets stucked after "heavier" testing 

### ISSUE THREAD

**Issue by tsusanka** [trezor/trezor-firmware#22] opened 2019-04-16 14:08 UTC
This is somewhat connected to https://github.com/trezor/trezor-core/issues/509. Although we have improved the behaviour it is still possible to get the trezor stucked. Steps to reproduce:

- do a recovery (or anything that leads to a keyboard on Trezor)
- press any button with letters, hold it and swipe to another button while holding
- sometimes the device gets stucked

I've built debug firmware and there is no error in the log. Strangely enough, I am sometimes able to perform some additional operations, so it is not a complete freeze.

Log: https://gist.github.com/tsusanka/f9837d06f227eae90718b42357c4cb74

**Comment by pankrats** [comment] 2019-05-28 12:32
It still happens with new firmware 2.1.1. during Recovery (and dry-run recovery). 

Also, with fw 2.1.1 touch screen **still stays** irresponsive even after web wallet reload. 

1. Do a dry-run recovery, device gets stuck at some point: 
![2019-05-28 14 27 55](https://user-images.githubusercontent.com/31442634/58478039-5765bf80-8155-11e9-8eae-249b9b97b6b7.jpg)

2. Refresh the web wallet (F5), result: 
![20190528142805 (1)](https://user-images.githubusercontent.com/31442634/58477986-3a30f100-8155-11e9-8ca6-564e71a63c67.gif)

**Comment by matejcik** [comment] 2019-05-28 12:58
@pankrats can you reproduce the freeze doing anything other than recovery? typing a long passphrase maybe?

**Comment by pankrats** [comment] 2019-05-28 13:58
@matejcik yes, it happens during the passphrase typing as well! 
but it's harder to reproduce.
![Uploading 20190528155347.gif…]()
![Uploading ho.gif…]()

The result after web wallet refresh is still the same (screen is irresponsive).

**Comment by matejcik** [comment] 2019-05-28 14:09
it's almost certainly #144 then :/

**Comment by GlitchXploitr** [comment] 2019-05-29 00:52
Is there an eta for a firmware update that will fix this issue? I just got my model T today and decided to dry test my seed before moving any funds to my trezor. Had the frozen screen issue on the first dry test while entering the 12th word. Firmware version 2.1.0

**Comment by ZdenekSL** [comment] 2019-06-26 12:51
Please, retest with new firmware 2.1.2

**Comment by ZdenekSL** [comment] 2019-08-22 12:08
Please, retest with new firmware 2.1.4

**Comment by bosomt** [comment] 2019-08-25 17:33
@ZdenekSL it's still in 2.1.5 fw version ;)

**Comment by tsusanka** [comment] 2019-08-26 10:50
@bosomt how "hard" was it to reproduce this?

**Comment by bosomt** [comment] 2019-08-26 13:38
@tsusanka i can always reproduce it via device passphrase enter dialogue
device stars to respond after wallet is refreshed

**Comment by matejcik** [comment] 2019-08-26 14:20
@bosomt please also test if you can reproduce the freeze when entering recovery words.

If not, let's close this issue and open a new one that is specific to passphrase entry. This particular issue has a history that is too deep and convoluted.

Also please test if this happens with a very long passphrase, or with short passphrase but large number of key presses (i.e., enter some letters, erase them, enter again, etc.)

**Comment by bosomt** [comment] 2019-08-27 08:31
@matejcik 
1) i think we can close it but maybe @pankrats wants to say something about it

2) it's not related to length, it freezes even with very shot passphrase,

3) i tried many recoveries of shamir seed so lots of typing and no freeze since last fix

**Comment by matejcik** [comment] 2019-08-27 11:30
OK, closing in favor of (very nice) #444

**Closed by matejcik** 2019-08-27 11:30 UTC
Labels: bug, core, firmware
