### ISSUE TITLE
Extra features:    Password Manager

### ISSUE THREAD

**Issue by wade-liwei** [trezor/trezor-firmware#1608] opened 2021-05-12 06:26 UTC
Password Manager.   soon on microSD card for Trezor Model T.

I want to sure:  Trezor Model T support storage password on microSD card right now  or  in the further   ?

**Comment by prusnak** [comment] 2021-05-12 07:19
Duplicate of https://github.com/trezor/trezor-firmware/issues/1608

**Closed by prusnak** 2021-05-12 07:19 UTC
Labels: enhancement, feature
