### ISSUE TITLE
Add device test for PIN change on Trezor T

### ISSUE THREAD

**Issue by andrewkozlik** [trezor/trezor-firmware#471] opened 2019-08-30 15:24 UTC
- Make it possible to enter a PIN into the Trezor T in device tests.
- Add device test for change PIN on Trezor T.

**Comment by prusnak** [comment] 2019-09-02 12:21
Currently, we cache the entered PIN on T1 in order to check whether the PIN was set correctly.

The question is whether we need to do the same for TT or there is a clever trick to perform this check differently (e.g. by returning PVC + all metadata required for checking whether the PIN corresponds to the currently tested PIN). If there is such trick I suggest to remove PIN caching in T1 and use the same method for both T1 and T2.

**Comment by matejcik** [comment] 2019-09-09 07:27
we could call change-pin again, and check that the new pin is accepted as "current pin"

**Comment by tsusanka** [comment] 2019-09-20 13:58
Looks like a duplicate of #228?

**Comment by prusnak** [comment] 2019-09-20 14:36
Closed via https://github.com/trezor/trezor-firmware/commit/65c1afa728ada4700f4afb710187300560e14079

**Closed by prusnak** 2019-09-20 14:36 UTC
Labels: P3 Medium, S4 Low, W3, core, tests
