### ISSUE TITLE
Allow longer EthereumSignMessage limit with "disable Safety Checks"

### ISSUE THREAD

**Issue by RealBigPenny** [trezor/trezor-firmware#2516] opened 2022-09-14 17:49 UTC
Creating a proposal on Snapshot.org involves signing a message including the entirety of the proposal. So a proposal which is longer than a couple of words, exceeds the Trezor set limit of 1024. Trezor is the only wallet (both hardware and software) which imposes such a low character limit, rendering it useless for the most used DeFi governance tool: Snapshot.org

I saw the past reasoning for imposing such a strict character limit which seems to be mainly driven by a single person and the fact that longer messages are beyond that particular persons personal use case. That stance does not line up with any other EVM compatible wallet, both hard and software.

If allowing bigger messages by default is out of question for some reason, I propose to create a temporary `unrestricted mode`, similar to how `Safety checks` can be disabled in TrezorSuite to enable usage with ETH testnet and other "non-standard" transactions.

**Comment by matejcik** [comment] 2022-09-14 20:18
Duplicate of #1909, please continue the discussion there.

Also this is not a matter of security, so "safety checks" wouldn't apply. It is a matter of technical limits.
Furthermore, this limit does not exist on the Trezor T, so if you are seeing issues, they might be something else.

**Closed by matejcik** 2022-09-14 20:18 UTC
Labels: code
