### ISSUE TITLE
Add support for TRON (TRX)

### ISSUE THREAD

**Issue by m-o-m12** [trezor/trezor-firmware#2165] opened 2022-03-09 10:43 UTC
**Is your feature request related to a problem? Please describe.**
As a [TRON](https://tron.network/) (TRX) user, I would like to store TRX and BTT coins on my Trezor Model T. Trezor supporting TRON will give us great convenience and  for Trezor, that will help attract more users.

**Describe the solution you'd like**
The Trezor firmware supports TRON(TRX).

**Additional context**
https://tron.network/

**Comment by prusnak** [comment] 2022-03-09 10:45
Duplicate of #1532

**Closed by prusnak** 2022-03-09 10:45 UTC
