### ISSUE TITLE
`sign-message` behaves strangely

### ISSUE THREAD

**Issue by ibz** [trezor/trezor-firmware#4361] opened 2024-11-18 13:59 UTC
**Describe the bug**

**Info** menu item should be on **Address**, but it shows on **Message** instead.

**Firmware version and revision**

`main` branch

**To Reproduce**

`trezorctl btc sign-message -n "m/44h/0h/0h/0/0" "HELLO asjidj askdfhsak jffhdsa kfjsdfha kfj afhsd fkjasdlh fkjasdh fkjlasdh fkjdasashf asdkl jfh 123 123"`

**Expected behavior**

* There should be an "info" menu item on the first screen, and none in the 2nd screen.

**Screenshots**

![image](https://github.com/user-attachments/assets/017d9375-de42-4806-957a-90109ac85be1)

**Comment by obrusvit** [comment] 2024-11-18 17:42
Duplicate of https://github.com/trezor/trezor-firmware/issues/4309 

Draft PR with a fix: https://github.com/trezor/trezor-firmware/pull/4354

**Closed by obrusvit** 2024-11-18 17:42 UTC
Labels: bug, T3T1
