### ISSUE TITLE
Stellar: invalid signature if timebounds are set to 0/0

### ISSUE THREAD

**Issue by quietbits** [trezor/trezor-firmware#1699] opened 2021-07-09 18:19 UTC
Trezor (both T1 and TT) conflate timebounds set to 0/0 with timebounds unset, and produce a signature for "timebounds unset". This is of course invalid if the incoming parameters are "set to 0/0"

---

### Original report:

**Describe the bug**
On [Stellar Laboratory](https://laboratory.stellar.org/) created a payment transaction without the upper time bound. The transaction was shown correctly on the device and signed. When validating the signature on the Laboratory, it was invalid. The signature validates correctly if the upper time bound is set.

**Firmware version and revision**
Trezor One v1.10.1

**Desktop/smartphone setup (please complete the following information):**
 - Wallet software: Trezor Wallet
 - OS: Windows and MacOS (Trezor Bridge v2.0.27)
 - Browser: Chrome v91.0.4472.124

**To Reproduce**
1. Go to [Laboratory](https://laboratory.stellar.org/)
2. Select `public` network (top right corner)
2. Click on "Build Transaction" tab and fill in:
- Source Account
- Transaction Sequence Number (click on Fetch... button)
- Select Payment in Operation Type dropdown
- Destination
- Asset `native`
- Amount
3. Click "Sign in Transaction Signer" at the bottom
4. Scroll to the bottom of the page and click "Sign with Trezor"
5. Follow the Trezor instructions
6. Should see "Success!" message that the signature was added
7. Click on "Submit in Transaction Submitter" at the bottom of the page
8. Scroll to the bottom of the page to view checked signatures

![image](https://user-images.githubusercontent.com/7346473/125119666-6dc5ff80-e0bf-11eb-9f18-adf7b13cf129.png)

**Expected behavior**
The upper time bound should not be required to validate the signature.

**Comment by matejcik** [comment] 2021-07-22 13:52
we can't currently verify this as the Laboratory doesn't want to create a transaction where lower bound is set but upper bound isn't.

**Comment by shanzzam** [comment] 2021-07-28 21:17
> we can't currently verify this as the Laboratory doesn't want to create a transaction where lower bound is set but upper bound isn't.

The issue in the Laboratory has been fixed with https://github.com/stellar/laboratory/pull/542

**Comment by matejcik** [comment] 2021-07-29 08:52
cannot reproduce the issue with [this XDR](https://laboratory.stellar.org/#xdr-viewer?input=AAAAAgAAAADjcmgwoLYMtfUshEz%2FzU7tZeulwVXomyZBFWJyTnHlRAAAAGQAAAAAAAAAKgAAAAEAAAAAABVcwAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAQAAAADjcmgwoLYMtfUshEz%2FzU7tZeulwVXomyZBFWJyTnHlRAAAAAAAAAAAAJiWgAAAAAAAAAAA&type=TransactionEnvelope)

steps:
1. load Trezor with the following mnemonic: `illness spike retreat truth genius clock brain pass fit cave bargain toe` (SEP-5 test vector)
2. use the above linked XDR for Transaction Signer
3. use the following secret key: `SBGWSG6BTNCKCOB3DIFBGCVMUPQFYPA2G4O34RMTB343OYPXU5DJDVMN`
4. also produce a signature with Trezor

result: both Laboratory and Trezor signature is identical

@quietbits is it possible that you encountered an instance of https://github.com/stellar/laboratory/pull/542 while you were testing this?

**Comment by quietbits** [comment] 2021-07-29 13:20
@matejcik I can reproduce this without any timebounds set on firmware 1.10.2. It's fine with min/max timebounds.

![image](https://user-images.githubusercontent.com/7346473/127498899-eda264ad-66a6-4864-8a83-1af384b254fc.png)

**Comment by matejcik** [comment] 2021-07-29 13:22
oh that. yeah, we know about that :)

**Comment by matejcik** [comment] 2021-07-29 13:24
I have updated the title and summary to match.

See also https://github.com/stellar/js-stellar-base/issues/438

Currently planned resolution for this issue is to reject "timebounds unset" and only correctly support "timebounds set" -- unless the discussion above goes the other way.

**Comment by quietbits** [comment] 2021-07-29 13:25
Great! Thanks for updating the issue to make it more clear. 👍

**Closed** 2021-09-24 08:30 UTC
Labels: core, legacy, altcoin, bug
