### ISSUE TITLE
Wallet creation, seed backup design

### ISSUE THREAD

**Issue by Hannsek** [trezor/trezor-firmware#3089] opened 2023-06-18 08:45 UTC
https://www.figma.com/file/l0gG9XeRJ8FTDQ3cfb1wv9/Trezor-T%2C-Trezor-One?type=design&node-id=8825-71197&t=4gMBHfDOelVRGYl9-4

**Comment by Hannsek** [comment] 2023-06-19 12:52
Thanks for that. 

As pagination on the `STANDARD BACKUP` page would "ruin" the header, let's not put it there.
![image](https://github.com/trezor/trezor-firmware/assets/57008159/db8e8fb5-1b8c-42e1-abbe-7f78d1f11b38)

> Also, with the left-arrow, just want to confirm (as I see it in other designs as well) that we have changed its appearance - it is always a "slim" arrow instead of the "fat" arrow as before?

Yes, with the one-fat-arrow design, the user is more guided in which direction he/she should continue.

**Comment by grdddj** [comment] 2023-06-19 14:47
> But user will be able to go up to the `STANDARD BACKUP` page by the up arrow. Is it ok from the code pov? @grdddj

I think it is fine implementation-wise.

To which point would the user be redirecting when selecting `CHECK AGAIN` after an unsuccessful "quiz" attempt?

**Comment by Hannsek** [comment] 2023-06-19 16:37
I'd say to this one below as the user wants to see the words. 
![image](https://github.com/trezor/trezor-firmware/assets/57008159/43da2eff-58d2-40c3-b77c-8d1ec5ee6447)

**Comment by grdddj** [comment] 2023-06-26 13:42
> I'd say to this one below as the user wants to see the words. ![image](https://user-images.githubusercontent.com/57008159/246887752-43da2eff-58d2-40c3-b77c-8d1ec5ee6447.png)

For simplicity purposes, currently, it moves to the previous page (`Write down all XX words`) - it is an edge case (caused by user error) and it would unnecessarily complicate the code to move in the middle of one flow

**Comment by Hannsek** [comment] 2023-07-04 10:37
Wallet creation - Shamir backup design: https://www.figma.com/file/l0gG9XeRJ8FTDQ3cfb1wv9/Firmware?type=design&node-id=8825-71198&mode=design&t=S14phM8hFc2KN54k-4

**Comment by grdddj** [comment] 2023-07-17 13:31
Merged in https://github.com/trezor/trezor-firmware/pull/3135

**Closed by grdddj** 2023-07-17 13:31 UTC
Labels: T2B1
