### ISSUE TITLE
No Signing for Rinkeby in Metamask

### ISSUE THREAD

**Issue by HeroHann** [trezor/trezor-firmware#1762] opened 2021-08-13 14:07 UTC
**Describe the bug**
When trying to sign a tx (no matter what exactly) while connected to metamask running the Rinkeby-testet (where swaps are enabled) a new tab opens, but the Trezor does not show anything and then the tab closes, tx does not go through.

**Firmware version and revision**
Trezor T: 2.4.1
Metamask: 10.0
MacOS

**To Reproduce**
Connect the Trezor T to Metamask
Change to Rinkeby
Try to send any tx.

**Expected behavior**
Should sign the tx, so users can test on testiest (especially, as suite does not support des swaps while metamask does and so this seems to be the way to test this)

**Additional context**
Roosten is working normally on metamask and Trezor Suite.

**Comment by prusnak** [comment] 2021-08-14 09:17
Duplicate of https://github.com/trezor/connect/issues/784

In short - Metamask uses wrong paths for Ethereum testnet networks (it should be m/44'/1' for testnet) and does not show the errors returned from Trezor Connect.

**Closed by prusnak** 2021-08-14 09:17 UTC
Labels: bug
