### ISSUE TITLE
Rust: `trezor-client`'s build script fails when `protoc` binary is not present

### ISSUE THREAD

**Issue by DaniPopes** [trezor/trezor-firmware#3153] opened 2023-07-15 11:14 UTC
**Describe the bug**
After the [`0.1.1` release](https://crates.io/crates/trezor-client/versions), [`trezor-client`](https://github.com/trezor/trezor-firmware/tree/b4825f408a5140af43ffcc1744e0df3c5fdf07be/rust/trezor-client) fails building when `protoc` binary is not present due to the addition of the build script.
This makes our CI [workflows fail on `ethers-rs`](https://github.com/gakonst/ethers-rs/actions/runs/5561045481/jobs/10159775784?pr=2510) when building with support for Trezor.

Given that the Rust protobuf bindings are platform agnostic, can their generation be included in the main makefile pipeline like with python's? This would remove the `protoc` dependency and compilation step from its users.

I'd be willing to work on this, if this is desired.

**Comment by prusnak** [comment] 2023-07-15 11:47
> I'd be willing to work on this, if this is desired.

It would be great if you could come up with a build request.

**Comment by prusnak** [comment] 2023-08-15 20:37
@DaniPopes Recently we pushed trezor-client crate v0.1.2. Can you please confirm that the issue is fixed with that release?

**Comment by prusnak** [comment] 2023-08-15 20:38
Ah, my bad. I was under impression that https://github.com/trezor/trezor-firmware/pull/3154 has been merged, but it hasn't.

**Closed** 2023-09-29 18:13 UTC
Labels: bug
