### ISSUE TITLE
Stellar Laboratory txn op Sponsor Future Reserves (incl. Stop Sponsoring in txn) fails

### ISSUE THREAD

**Issue by JFWooten4** [trezor/trezor-firmware#1758] opened 2021-08-12 00:12 UTC
When signing txns using Stellar Lab with Trezor, the device freezes and the signature fails when trying to sponsor future reserves via the start and stop ops in a trasaction

**Comment by matejcik** [comment] 2021-08-12 08:21
duplicate of #1691

**Closed by matejcik** 2021-08-12 08:21 UTC
Labels: bug
