### ISSUE TITLE
UI: sometimes the word 'Swipe' and the scrollbar aren't shown

### ISSUE THREAD

**Issue by leshik** [trezor/trezor-firmware#871] opened 2020-02-22 12:29 UTC
**Describe the bug**

While playing with the Model T emulator, I encountered a small glitch. When setting up the wallet (Shamir backup), it shows 20 words in portions. You have to swipe to see the next one. At the bottom of the screen, there is an arrow and the word 'Swipe'. I found that sometimes this word and the scrollbar are shown and sometimes they aren't. I didn't find any pattern, it's just random. Not very important, but looks strange.

**Firmware version or revision**

Current master.

**Expected behavior**

The word 'Swipe' and the scrollbar should be shown every time the arrow is shown and a user has to swipe.

**Comment by bosomt** [comment] 2022-09-02 10:22
@leshik can we close this issue ?
so far we were not able to reproduce.

**Closed** 2022-09-02 20:19 UTC
Labels: core, bug
