### ISSUE TITLE
[Cardano] Invalid Witness Request when signing Cardano transaction with withdrawal

### ISSUE THREAD

**Issue by burtbot25** [trezor/trezor-firmware#2387] opened 2022-07-14 20:50 UTC
**Describe the bug**
I'm having problems signing with Trezor Connect when trying to sign a withdrawal transaction, but only when I'm using a staking path that is not the first account.

For example:

When signing a Cardano withdrawal transaction with **m/1852'/1815'/0'/2/0** in the withdrawal parameters, signing is successful.

However, signing fails when signing a withdrawal made on a staking path of a different account such as **m/1852'/1815'/1'/2/0** or **m/1852'/1815'/2'/2/0**. In these cases I get an "**Invalid witness request**" error returned from trezor and I am unable to get a signature.

**Firmware version and revision**
2.5.1

**Desktop/smartphone setup (please complete the following information):**
 - Wallet software: Trezor Connect
 - OS: Windows
 - Browser: Chrome
 - Version: 104.0

**To Reproduce**
1. Create an ordinary transaction which include Withdrawal parameters
e.g.,: "withdrawals":[{"path":"m/1852'/1815'/1'/2/0","amount":"2182345"}]
2. Using web Trezor connect, confirm signing
3. Confirm signing on Trezor (Model T)
4. After "Hold to confirm", "Invalid witness request" error appears in the browser console

**Expected behavior**
Successfully sign the transaction and return a signature

EDIT:
In my previous tests when signing, I had the path for my inputs as **m/1852'/1815'/0'/0/0** when signing with staking paths of **m/1852'/1815'/1'/2/0** and **m/1852'/1815'/2'/2/0**.  When I decided to match the account number of the input path and staking path, I no longer got the error (e.g., input path: **m/1852'/1815'/1'/0/0** and staking path: **m/1852'/1815'/1'/2/0**).

Is it only possible to withdraw rewards into the same account? I was under the impression that it should be possible to withdraw rewards into a different account (i.e., input path **m/1852'/1815'/0'/0/0** , staking path **m/1852'/1815'/1'/0/0** )

**Comment by matejcik** [comment] 2022-07-15 13:09
cc @davidmisiak or @gabrielKerekes

**Comment by gabrielKerekes** [comment] 2022-07-18 10:31
This is a safety feature and expected behaviour. We don't allow using multiple accounts in a single transaction. The issue was with the possibility of an attacker sending the user's funds to different accounts (owned by the user). Outputs containing an address belonging to any of the user's accounts were considered change outputs and wouldn't be displayed to the user which would allow an attacker to deanonymize the user's accounts without the user even knowing about it.

While implementing this feature we also decided to extend the "policy" to all the transaction elements. And so you can not make a cross-account withdrawal. I admit this might be a bit of an overkill for withdrawals as their path was always being shown, but this won't be true anymore with the introduction of "expert mode" (https://github.com/trezor/trezor-firmware/pull/2355) which should be included in the next release.

There's extensive conversation on the topic in https://github.com/trezor/trezor-firmware/pull/1683#discussion_r689517936.

**Comment by matejcik** [comment] 2022-07-18 10:42
thanks, I was not sure how withdrawals plug into this.
closing as intended behavior.

**Closed by matejcik** 2022-07-18 10:42 UTC
Labels: bug
