### ISSUE TITLE
Red alert wipe code why?

### ISSUE THREAD

**Issue by europound** [trezor/trezor-firmware#2260] opened 2022-05-08 14:52 UTC
Why don't you want to remove a red alert after wipe code entered?
what is the reasoning? if it is under duress, and plausible deny is a good thing

**Comment by prusnak** [comment] 2022-05-08 17:10
Duplicate of https://github.com/trezor/trezor-firmware/issues/2055

**Closed by prusnak** 2022-05-08 17:10 UTC
Labels: feature
