### ISSUE TITLE
Trezor temporarily displays the (1,1) monero address when asked for (1,0) if no passphrase is used

### ISSUE THREAD

**Issue by chaserene** [trezor/trezor-firmware#2811] opened 2023-02-09 11:45 UTC
**Describe the bug**
if I generate a new wallet in the Monero GUI from a Trezor model T without a passphrase, generate a new account (`1`) and then ask Monero GUI to display the 0th address of that account (`1,0`) on the Trezor, the Trezor will show the address 1st address (`1,1`). this ceases to be the case once I either

* generate `1,1` and view it, or
* I close the wallet and reopen.

Also, I can't reproduce the bug if I use a passphrase.

I understand that this could be a bug in the Monero GUI codebase as well, so me posting here is just a guess that the bug is in the firmware.

**Firmware version and revision**
core/2.5.3

**Desktop/smartphone setup (please complete the following information):**
 - Wallet software: Monero GUI 18.1.2
 - OS: GNU/Linux Debian 11

**To Reproduce**
1. take an initialized Trezor model T. I tested with the below mnemonics and disabled the PIN. in the later steps I'll use addresses from the first mnemonic:
  * abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about
  * abandon ability able about above absent absorb abstract absurd abuse access ability
3. set up a wallet from it in Monero GUI.
4. when asked for a passphrase, choose to enter it on the Trezor and don't enter anything, just approve the empty string.
5. in Monero GUI, go to Receive, click "Show on device". this is (0,0). see that the addresses match here (`44jKQv6Z...`).
6. in Account, create a new account (I named it "1").
7. perform the same check for this account's 0th address (1,0). Monero GUI (`89gMN28N...`) and the Trezor (`87p7uZBu...`) show different addresses.
8. generate a new address in this account (1,1) (I named it "1") and perform the same check. the addresses match here (`87p7uZBu...`).
9. perform the check for (1,0) again. there is no discrepancy now, both Monero GUI and the Trezor show `89gMN28N...`.

**Expected behavior**
I expect the Trezor to always show the address that I instruct it to display.

**Comment by prusnak** [comment] 2023-02-09 11:48
@ph4r05 Can you reproduce the issue? Any ideas?

**Comment by ph4r05** [comment] 2023-02-09 11:51
Thanks for the ping, however I am super busy right now, can get back to it in like 1-3 weeks.

**Comment by matejcik** [comment] 2023-02-17 10:43
given that the problem goes away after closing/opening the wallet, and given that Trezor doesn't really store state between monero calls, this is overwhelmingly likely to be a Monero GUI issue, not a firmware issue.

Also I can't reproduce with Monero GUI 0.18.1.2 and current master.

**Closed by matejcik** 2023-02-17 10:43 UTC
Labels: bug

**Comment by prusnak** [comment] 2023-02-17 19:52
Worth checking out - can these be related? https://github.com/monero-project/monero-gui/issues/4105
