### ISSUE TITLE
Separate ButtonRequests in device

### ISSUE THREAD

**Issue by vladimirvolek** [trezor/trezor-firmware#18] opened 2018-11-15 17:10 UTC
We have 2 step verifying in this section(screenshot). First one is an address, second one is a message. We want to know which one is verifying. Currently both responses have "ButtonRequest_Other".

![image](https://user-images.githubusercontent.com/3112191/48568860-95f60400-e900-11e8-8a54-dabba7bdc399.png)

**Comment by prusnak** [comment] 2019-06-26 14:37
Duplicate of https://github.com/trezor/trezor-firmware/issues/35

**Closed by prusnak** 2019-06-26 14:37 UTC
Labels: P4 Low, common, enhancement, protobuf
