### ISSUE TITLE
FIDO2 support - Unable to load resident keys: requested feature not supported - openssh8.2 linux

### ISSUE THREAD

**Issue by zejdlikt** [trezor/trezor-firmware#1393] opened 2020-12-17 21:31 UTC
Hello, 

i am trying to use resident key method authentication using openssh 8.2 (OpenSSH_8.2p1 Ubuntu-4ubuntu0.1, OpenSSL 1.1.1f  31 Mar 2020) [described here](https://www.stavros.io/posts/u2f-fido2-with-ssh/)

**Firmware version and revision**
- Trezor T with fw 2.3.4 
- trezorctl v0.12.2
- trezor-bridge_2.0.27

**Desktop/smartphone setup (please complete the following information):**
 - OS: Linux 

**To Reproduce**
- generate a key on server A
`ssh-keygen -t ecdsa-sk -O resident -f ~/.ssh/id_mykey_sk -O application="ssh:user@server.domain.com"` 

- use `~/.ssh/id_mykey_sk.pub` and add it to the authorized keys on server A
- (optionally) remove private key `~/.ssh/id_mykey_sk`

- move to the server B, connect TrezorT USB and run `ssh-add -K -v` and the output:

```
serverB:~/.ssh$ ssh-add -K -vvvvv
Enter PIN for authenticator:  <ENTER>
debug3: start_helper: started pid=394515
debug3: ssh_msg_send: type 5
debug3: ssh_msg_recv entering
debug1: start_helper: starting /usr/lib/openssh/ssh-sk-helper 
debug1: sshsk_load_resident: provider "internal"
debug1: ssh_sk_load_resident_keys: trying /dev/hidraw3
debug1: read_rks: get metadata for /dev/hidraw3 failed: FIDO_ERR_INVALID_ARGUMENT
debug1: ssh_sk_load_resident_keys: read_rks failed for /dev/hidraw3
debug1: ssh-sk-helper: reply len 4
debug3: ssh_msg_send: type 5
debug3: reap_helper: pid=394515
```
- no key is being present in `ssh-add -L`
- key is present in TrezorT when listing records using `trezorctl  fido credentials list`
```
 $ trezorctl  fido credentials list
Please confirm action on your Trezor device.

WebAuthn credential at index 0:
  Relying party ID:       ssh:user@server.domain.com
  User ID:                0000000000000000000000000000000000000000000000000000000000000000
  User name:              openssh
  User display name:      openssh
  Creation time:          22
  hmac-secret enabled:    False
  Use signature counter:  True
  Algorithm:              EdDSA
  Curve:                  Ed25519
  Credential ID:          f1d0020013ee3bceac632abd70594fb6476e6f23053d09d8b187a64bbe2f9837ef6928cd18307456b229e6bd7bfd4a996a70ac3171c1a4d67bb5a78b4288c35xec06ee1e49c206024f8ef4bbad3dcf1c87e68f1c3b0a256a906e5d721e429dd65b6b793e25de070c672fdf799bb1800f92650925fz1c34f14e2037aa65
```

**Expected behavior**
Key should be imported into the openssh authentication agent

**Comment by prusnak** [comment] 2020-12-17 23:05
Duplicate of https://github.com/trezor/trezor-firmware/issues/877

**Closed by prusnak** 2020-12-17 23:05 UTC
Labels: bug
