### ISSUE TITLE
Device tests on device freeze

### ISSUE THREAD

**Issue by onvej-sl** [trezor/trezor-firmware#1479] opened 2021-02-16 12:27 UTC
When running `poetry run pytest tests/device_tests/test_msg_signtx_segwit.py`, the device (not emulator) gets stuck waiting for user interaction:

![image](https://user-images.githubusercontent.com/38104856/108061609-db15bd00-7058-11eb-8e16-34a83a733567.png)

I bisected it and it looks like it was introduced in  f1382bf89250b5e0a130ac89704bab9c11ec651a. 

@mmilata

**Comment by mmilata** [comment] 2021-02-17 12:05
Thanks for the report! It's good to know f1382bf made things worse even though the total number of allocations seems to have decreased. Let me close this as a duplicate of #1371 since I'm 99% sure the root cause is the same. Btw on btconly firmware the testcase works fine if you are using it for testing your changes.

**Closed by mmilata** 2021-02-17 12:05 UTC
Labels: TT, bug, tests
