### ISSUE TITLE
eth_signTypedData Support EIP-712

### ISSUE THREAD

**Issue by notesbytom** [trezor/trezor-firmware#1523] opened 2021-03-07 22:50 UTC
**Is your feature request related to a problem? Please describe.**
The currently implemented ethereum_message_sign here https://github.com/trezor/trezor-firmware/blob/master/legacy/firmware/ethereum.c uses the prefix "\x19" "Ethereum Signed Message:\n" which is not compatible with eth_signTypedData from EIP-712 here https://eips.ethereum.org/EIPS/eip-712 .
I cannot find any workaround with lower-level crypto primitives to create a compatible typed data ethereum signature using the Trezor user exposed functions. 

**Describe the solution you'd like**
I would like to be able to sign Ethereum Typed Data with the trezor  using a programming interface like with python, or cli tool like trezorctl.

**Describe alternatives you've considered**
I have looked for crypto primitive functions available through programming interface or trezorctl to compose my own solution but did not find low enough level functionality to do this without writing custom firmware.

**Additional context**
Metamask lists the limitation here https://docs.metamask.io/guide/signing-data.html#signing-data-with-metamask .
*"Trezor and Ledger hardware wallets ... currently only support signing data using the `personal_sign` method"*
It would be great for Trezor implement functionality to do this before Ledger.
Compound Finance community governance has implemented "gas-free" signature-based voting at https://comp.vote/ but hardware wallets cannot be used for gas-free voting unless support is added to sign typed ethereum data. These signatures are relayed to create on-chain votes by Compound community governance volunteers. This allows Compound to pay the gas fees for votes encouraging participation in governance.

**Comment by prusnak** [comment] 2021-03-08 08:38
Duplicate of https://github.com/trezor/trezor-firmware/issues/1272

**Closed by prusnak** 2021-03-08 08:38 UTC
Labels: enhancement, feature
