### ISSUE TITLE
Support TRON Blockchain

### ISSUE THREAD

**Issue by hitlxy** [trezor/trezor-firmware#2102] opened 2022-02-06 05:29 UTC
TRON blockchain has a large community of users and developers. and Trezor is one of the best Cold wallet in the market, but now trezor does not support TRON(TRX), it's weird. Please add support for TRON(TRX), thanks a lot.

**Comment by prusnak** [comment] 2022-02-06 09:12
Duplicate of https://github.com/trezor/trezor-firmware/issues/1532

**Closed by prusnak** 2022-02-06 09:12 UTC
