### ISSUE TITLE
Add support for TRON (TRX)

### ISSUE THREAD

**Issue by vivian-kang** [trezor/trezor-firmware#2047] opened 2022-01-05 07:04 UTC
**Is your feature request related to a problem? Please describe.**
TRON (TRX) is the 27th biggest cryptocurrency according to Coinmarketcap. and users would like to store TRX coins on Trezor device, it would be important for them to be able to store their coins securely, so It'd be fantastic if Trezor supports TRX.

**Describe the solution you'd like**
Whatever allows TRX to be stored and transferred from a Trezor One / Trezor T .

**Describe alternatives you've considered**
[Ledger Wallet](https://support.ledger.com/hc/en-us/articles/360006904193-TRON-TRX-?docs=true)

Additional context
https://tron.network/

**Comment by prusnak** [comment] 2022-01-05 09:00
Duplicate of https://github.com/trezor/trezor-firmware/issues/1532

**Closed by prusnak** 2022-01-05 09:00 UTC
Labels: altcoin, product, community firmware
