### ISSUE TITLE
compute checksum word from manually entered incomplete seed

### ISSUE THREAD

**Issue by zdeneksvarc** [trezor/trezor-firmware#1498] opened 2021-02-24 09:48 UTC
**Is your feature request related to a problem? Please describe.**
When using diceware I can't compute checksum only with pen and paper. If I don't want to use computer, even offline, I can still use the trezor device. Why don't let the trezor device generate the checksum word from manually entered incomplete seed? 

**Describe the solution you'd like**
trezorctl command to turn on Trezor to compute BIP-39/SLIP-39 checksum word from manually entered incomplete seed.

**Describe alternatives you've considered**
Computing checksum word with software utility like [bip39check](https://github.com/bharathrao/bip39check ) in trusted offline environment like [Tails](https://tails.boum.org/).

**Additional context**
`trezorctl get-checksum -w [bip39|slip39] -t [128|192|256]`

**Comment by matejcik** [comment] 2021-02-24 09:50
basically a dup of #23

**Comment by prusnak** [comment] 2021-02-24 12:03
Closing as duplicate of https://github.com/trezor/trezor-firmware/issues/23

**Closed by prusnak** 2021-02-24 12:03 UTC
Labels: enhancement, feature
