### ISSUE TITLE
PIN delete button (yellow back arrow)

### ISSUE THREAD

**Issue by Hannsek** [trezor/trezor-firmware#2667] opened 2022-11-30 13:14 UTC
**Describe the bug**
PIN entry page.
When user clicks on the yellow back arrow, it deletes all already typed characters, not only one.

**Firmware version and revision**
2.5.2

**To Reproduce**
1. type several numbers on PIN entry page
2. press yellow back arrow
3. It deletes all entered numbers

**Expected behavior**
It should delete only one number.

**Comment by sime** [comment] 2022-11-30 13:35
@Hannsek I think this is already resolved in UI2.

e.g. https://github.com/trezor/trezor-firmware/pull/2227

@mmilata Could you confirm?

**Comment by matejcik** [comment] 2022-11-30 13:41
yeah this is a duplicate of https://github.com/trezor/trezor-firmware/issues/1469

**Closed** 2022-11-30 13:42 UTC
Labels: core, bug
