### ISSUE TITLE
Firmware error message in Wallet after setting a white noise screen

### ISSUE THREAD

**Issue by sorooris** [trezor/trezor-firmware#1222] opened 2020-08-24 17:05 UTC
**Describe the bug**
A Firmware error message is displayed after setting a white noise homescreen in MyTrezor Wallet.

**Firmware version and revision**
2.3.3 e137f19

**Setup:**
 - Wallet software: MyTrezor production [commit](https://github.com/satoshilabs/mytrezor/commits/ec6b4d36cbae2ec1c3f479eb3c1891090790b7c0)
 - OS: any (tested NixOS)
 - Browser: any (tested Chromium 84.0.4147.89)

**Steps to Reproduce**
1. Navigate to _Homescreen settings_ in Wallet,
2. Select and upload a white noise homescreen,
3. Confirm and see error.

**Expected behavior**

**Additional context**
Console returns `trezor.js] [call] Received Failure`.

**Screenshots**
![233-e137f19-firmwareerror](https://user-images.githubusercontent.com/10185314/91073602-9b3ac380-e63b-11ea-8014-8dd186ce8e15.png)

**Comment by sorooris** [comment] 2020-08-24 17:10
Same behavior in Suite: beta, [commit](https://github.com/trezor/trezor-suite/commit/74b74b0c70658ff4cad66541441aa7274f949308)
2.3.3 e137f19

> ![233-e137f19-firmwareerror-suite](https://user-images.githubusercontent.com/10185314/91074831-6465ad00-e63d-11ea-9bd6-c3304a5ed7e7.png)

**Comment by tsusanka** [comment] 2020-08-24 18:08
@sorooris could you append the white noise image here pls? I think we should write a test for it :)

**Comment by sorooris** [comment] 2020-08-24 21:55
@tsusanka 
![white-noise](https://user-images.githubusercontent.com/10185314/91100307-3bf1a900-e665-11ea-8ede-1f559f5117c4.png)

**Comment by tsusanka** [comment] 2020-08-25 08:27
I have added test in b2c63b72d6dea1aa87e62fd47776a1aaddb2e97a and it indeed fails even on an emulator. @mmilata could you look into it?

```
File "trezor/loop.py", line 191, in _step
  File "apps/base.py", line 242, in wrapper
  File "apps/management/apply_settings.py", line 52, in apply_settings
  File "apps/management/apply_settings.py", line 27, in validate_homescreen
AttributeError: 'Display' object has no attribute 'toif_info'
```

**Comment by matejcik** [comment] 2020-08-25 08:28
isn't this a duplicate of #1114 ?
can you reproduce the problem using trezorctl on a freshly plugged in TT? If not, it's a duplicate.

do other homescreens work? if yes, @tsusanka's problem is something else (mismatched trezor-core build perhaps?)

**Comment by matejcik** [comment] 2020-08-25 08:29
also let's not add whitenoise to tests, or else mark them as xfail or something; whitenoise homescreen is currently not guaranteed to work on hardware unless it's freshly plugged in

**Comment by tsusanka** [comment] 2020-08-25 08:34
Ah, I saw `File "apps/management/apply_settings.py", line 27, in validate_homescreen` and directly thought it was introduced by https://github.com/trezor/trezor-firmware/issues/1118. Ok @sorooris please retest what @matejcik says.

**Comment by sorooris** [comment] 2020-08-25 08:38
@matejcik please could you specify what "freshly plugged in TT" is?

Using the same white noise screen file with trezorctl (`trezorctl set-homescreen -f white-noise.png`) with a reconnected 2.3.3 e137f19 returns the following:

`[seb:/home/dir]$ trezorctl set-homescreen -f white-noise.png 
Traceback (most recent call last):
  File "/nix/store/pacl0pp9jnd6p706qw9a8mxkxqpx3ar8-python3.7-trezor-0.12.0/bin/.trezorctl-wrapped", line 9, in <module>
    sys.exit(cli())
  File "/nix/store/cqxkmww7dlic0qfskpmcd3xmckhsf6mi-python3.7-click-7.1.2/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/nix/store/cqxkmww7dlic0qfskpmcd3xmckhsf6mi-python3.7-click-7.1.2/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/nix/store/cqxkmww7dlic0qfskpmcd3xmckhsf6mi-python3.7-click-7.1.2/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/nix/store/cqxkmww7dlic0qfskpmcd3xmckhsf6mi-python3.7-click-7.1.2/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/nix/store/cqxkmww7dlic0qfskpmcd3xmckhsf6mi-python3.7-click-7.1.2/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/nix/store/cqxkmww7dlic0qfskpmcd3xmckhsf6mi-python3.7-click-7.1.2/lib/python3.7/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/nix/store/pacl0pp9jnd6p706qw9a8mxkxqpx3ar8-python3.7-trezor-0.12.0/lib/python3.7/site-packages/trezorlib/cli/__init__.py", line 78, in trezorctl_command_with_client
    return func(client, *args, **kwargs)
  File "/nix/store/pacl0pp9jnd6p706qw9a8mxkxqpx3ar8-python3.7-trezor-0.12.0/lib/python3.7/site-packages/trezorlib/cli/settings.py", line 114, in homescreen
    from PIL import Image
ModuleNotFoundError: No module named 'PIL'
`

**Comment by tsusanka** [comment] 2020-08-25 08:40
@sorooris are you in our repository inside `nix-shell`? Because this sounds like a "host" problem

**Comment by matejcik** [comment] 2020-08-25 08:45
@sorooris "freshly plugged" is you unplug, then replug, then do the thing without doing anything else with the device.

please also try setting the whitenoise homescreen as first thing through wallet. @bosomt was successful with that last time

**Comment by prusnak** [comment] 2020-08-25 08:51
@seb `No module named 'PIL' ` => your installation is missing python-pillow package; i guess we need to fix that in the nix package

@tsusanka `AttributeError: 'Display' object has no attribute 'toif_info'` => it seems you forgot to rebuild the emulator

**Comment by matejcik** [comment] 2020-08-25 08:59
Ah, also trezorctl doesn't support png files for TT.

we have code that enables it, but it's currently internal ... i'm a little reluctant to move it to the main package, but perhaps we could?

**Comment by tsusanka** [comment] 2020-08-25 09:02
Confirming the test I have written has passed after I have rebuilt _core_. Apologies :roll_eyes:.

**Comment by sorooris** [comment] 2020-08-25 10:09
@matejcik Thanks for clearing that up:
using the _bad-noise.toif_ file with `trezorctl set-homescreen -f bad-noise.toif` command works and returns the correct error [message](https://github.com/trezor/trezor-firmware/issues/1118#issuecomment-678980669). However, I'm unable to verify in Wallet/Suite since .toif files are not allowed there.

**Comment by matejcik** [comment] 2020-08-25 10:12
please try with "good" noise.toif too. If that succeeds from trezorctl on a freshly-plugged TT, we can close the issue as a duplicate of #1114

**Comment by sorooris** [comment] 2020-08-25 12:18
QA OK
The "good" white noise (white-noise.toif from Slack) is set seamlessly via trezorctl; let's close it as a duplicate of the #1114 issue.

**Comment by matejcik** [comment] 2020-08-25 12:27
thanks! closing

**Closed by matejcik** 2020-08-25 12:27 UTC
Labels: bug
