### ISSUE TITLE
Confirmation dialog displayed halfway through signing animation

### ISSUE THREAD

**Issue by sorooris** [trezor/trezor-firmware#1106] opened 2020-07-14 11:08 UTC
**Describe the bug**
Transaction confirmation dialog is displayed halway through the signing animation.

**Firmware version and revision**
T1 1.9.1 c6b2580, 1.9.2 b8127c59
TT 2.3.2 b8127c59

**Desktop/smartphone setup (please complete the following information):**
 - Wallet software: Suite develop, 232-pinentry; Wallet [autolock branch](https://github.com/satoshilabs/mytrezor/commits/0e7d8b1992b17a0e76f6a105ad9ae2c41ad4cbe0), [production](https://github.com/satoshilabs/mytrezor/commits/eb820d9b7fa3c41240b4fa98d2a2bb39d06646d3)
 - OS: Nixos
 - Browser: Chromium 80.0.3987.149
 - Coin: BTC

**To Reproduce**
1. navigate to Send dialog
2. confirm transaction in the Wallet
3. see device screen

**Expected behavior**
Confirmation dialog is displayed before or after the _signing transaction_ animation.

**Screenshots**
Device screen:
![Peek 2020-07-14 13-14](https://user-images.githubusercontent.com/10185314/87419595-0ff9f700-c5d4-11ea-8dad-8e7a3ee999e7.gif)
Wallet screen:
![Peek 2020-07-14 12-25](https://user-images.githubusercontent.com/10185314/87416832-9102bf80-c5cf-11ea-8de7-e6761ab12157.gif)

**Additional context**
Animation is also slowed down compared to previous device firmwares and wallet/suite versions.

**Comment by tsusanka** [comment] 2020-07-16 09:34
Duplicate of  #1109.

**Closed by tsusanka** 2020-07-16 09:34 UTC
Labels: Product Owner, bug
