### ISSUE TITLE
Update micropython to support gcc 13 and Python 3.11

### ISSUE THREAD

**Issue by winksaville** [trezor/trezor-firmware#3641] opened 2024-03-22 23:46 UTC
**Describe the bug**
My development environment is an Arch Linux Rolling release, hence my tools are generally the "latest" released versions and use gcc 13 and Python 3.11. Because [`vendor/micropython` v1.91.1](https://docs.micropython.org/en/v1.19.1/) is nearly 2 years old it is not compatible with gcc 13 and python 3.11.

Trying to `make build_unix` produces the following error:
```
vendor/micropython/py/stackctrl.c
vendor/micropython/py/stackctrl.c: In function ‘mp_stack_ctrl_init’:
vendor/micropython/py/stackctrl.c:32:32: error: storing the address of local variable ‘stack_dummy’ in ‘mp_state_ctx.thread.stack_top’ [-Werror=dangling-pointer=]
   32 |     MP_STATE_THREAD(stack_top) = (char *)&stack_dummy;
vendor/micropython/py/stackctrl.c:31:18: note: ‘stack_dummy’ declared here
   31 |     volatile int stack_dummy;
      |                  ^~~~~~~~~~~
In file included from vendor/micropython/py/runtime.h:29,
                 from vendor/micropython/py/stackctrl.c:27:
vendor/micropython/py/mpstate.h:323:23: note: ‘mp_state_ctx’ declared here
  323 | extern mp_state_ctx_t mp_state_ctx;
      |                       ^~~~~~~~~~~~
cc1: all warnings being treated as errors
scons: *** [build/unix/vendor/micropython/py/stackctrl.o] Error 1
make: *** [Makefile:266: build_unix] Error 2
```

**Firmware version and revision**
I'm attempting to use `make build_unix` on main:
```
(trezor-firmware-py3.11) wink@3900x 24-03-22T22:10:07.500Z:~/prgs/forks/trezor-firmware (main)
$ git log -1 --oneline
58c480f1a (HEAD -> main, origin/main, origin/HEAD) feat: Remove pyblake2
(trezor-firmware-py3.11) wink@3900x 24-03-22T22:10:17.258Z:~/prgs/forks/trezor-firmware (main)
```

**Desktop/smartphone setup (please complete the following information):**
```
wink@3900x 24-03-22T22:04:22.526Z:~
$ inxi
CPU: 12-core AMD Ryzen 9 3900X (-MT MCP-) speed/min/max: 2266/2200/4672 MHz
Kernel: 6.8.1-arch1-1 x86_64 Up: 1d 1h 44m Mem: 6.57/31.27 GiB (21.0%)
Storage: 1.82 TiB (35.3% used) Procs: 502 Shell: Bash inxi: 3.3.33
wink@3900x 24-03-22T22:04:32.923Z:~
$ gcc --version
gcc (GCC) 13.2.1 20230801
Copyright (C) 2023 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

wink@3900x 24-03-22T22:04:37.663Z:~
$ python --version
Python 3.11.8
wink@3900x 24-03-22T22:04:43.194Z:~
$ 
```

**To Reproduce**
 * git clone --recurse-submodules git@github.com:trezor/trezor-firmware
 * cd trezor-firmware
 * cp ../trezor-firmware-rust-toolchain.toml rust-toolchain.toml
 * cat rust-toolchain.toml 
 * poetry install --no-root
 * cd core
 * poetry shell
 * rustc --version
 * gcc --version
 * python --version
 * make JOBS=1 build_unix
```
 wink@3900x 24-03-22T23:20:15.455Z:~/prgs/forks
$ git clone --recurse-submodules git@github.com:trezor/trezor-firmware
Cloning into 'trezor-firmware'...
remote: Enumerating objects: 173899, done.
remote: Counting objects: 100% (11103/11103), done.
remote: Compressing objects: 100% (4396/4396), done.
remote: Total 173899 (delta 7854), reused 8862 (delta 6585), pack-reused 162796
Receiving objects: 100% (173899/173899), 145.58 MiB | 18.18 MiB/s, done.
Resolving deltas: 100% (129864/129864), done.
Submodule 'crypto/tests/wycheproof' (https://github.com/google/wycheproof) registered for path 'crypto/tests/wycheproof'
Submodule 'vendor/QR-Code-generator' (https://github.com/nayuki/QR-Code-generator.git) registered for path 'vendor/QR-Code-generator'
Submodule 'vendor/cmsis_5' (https://github.com/ARM-software/CMSIS_5.git) registered for path 'vendor/cmsis_5'
Submodule 'vendor/cmsis_device_u5' (https://github.com/STMicroelectronics/cmsis_device_u5.git) registered for path 'vendor/cmsis_device_u5'
Submodule 'vendor/fido2-tests' (https://github.com/trezor/fido2-tests.git) registered for path 'vendor/fido2-tests'
Submodule 'legacy/libopencm3' (https://github.com/libopencm3/libopencm3.git) registered for path 'vendor/libopencm3'
Submodule 'vendor/micropython' (https://github.com/trezor/micropython.git) registered for path 'vendor/micropython'
Submodule 'legacy/vendor/nanopb' (https://github.com/nanopb/nanopb.git) registered for path 'vendor/nanopb'
Submodule 'vendor/secp256k1-zkp' (https://github.com/bitcoin-core/secp256k1.git) registered for path 'vendor/secp256k1-zkp'
Submodule 'vendor/stm32u5xx_hal_driver' (https://github.com/trezor/stm32u5xx_hal_driver.git) registered for path 'vendor/stm32u5xx_hal_driver'
Cloning into '/home/wink/prgs/forks/trezor-firmware/crypto/tests/wycheproof'...
remote: Enumerating objects: 4455, done.        
...
Receiving objects: 100% (1017/1017), 13.08 MiB | 18.10 MiB/s, done.
Resolving deltas: 100% (570/570), done.
Submodule path 'vendor/micropython/lib/fsp': checked out '55bffd3a71cbeed2104cf30e7a39b641d8c1ff48'
Submodule path 'vendor/micropython/lib/stm32lib': checked out 'eb80f0126e50687aac966f4c39a2b5a5deffbe78'
Submodule path 'vendor/micropython/lib/wiznet5k': checked out '0803fc519ad7227e841287fb3638d6c8b2f111a1'
Submodule path 'vendor/nanopb': checked out 'c9124132a604047d0ef97a09c0e99cd9bed2c818'
Submodule path 'vendor/secp256k1-zkp': checked out '346a053d4c442e08191f075c3932d03140579d47'
Submodule path 'vendor/stm32u5xx_hal_driver': checked out '270974ea816779656ac8bb183344ac017e693677'
wink@3900x 24-03-22T23:21:43.467Z:~/prgs/forks
$ cd trezor-firmware
wink@3900x 24-03-22T23:22:12.679Z:~/prgs/forks/trezor-firmware (main)
$ cp ../trezor-firmware-rust-toolchain.toml rust-toolchain.toml
wink@3900x 24-03-22T23:22:30.535Z:~/prgs/forks/trezor-firmware (main)
$ cat rust-toolchain.toml 
[toolchain]
channel = "nightly"

wink@3900x 24-03-22T23:22:42.768Z:~/prgs/forks/trezor-firmware (main)
$ poetry install --no-root
Creating virtualenv trezor-firmware in /home/wink/prgs/forks/trezor-firmware/.venv
Installing dependencies from lock file

Package operations: 87 installs, 1 update, 0 removals

  - Installing attrs (21.4.0)
  - Installing certifi (2023.7.22)
...
  - Installing toiftool (0.1.0 /home/wink/prgs/forks/trezor-firmware/python/tools/toiftool)
  - Installing trezor-pylint-plugin (0.1.0 /home/wink/prgs/forks/trezor-firmware/tools/trezor-pylint-plugin)
wink@3900x 24-03-22T23:22:57.121Z:~/prgs/forks/trezor-firmware (main)
$ cd core
wink@3900x 24-03-22T23:23:02.287Z:~/prgs/forks/trezor-firmware/core (main)
$ poetry shell
Spawning shell within /home/wink/prgs/forks/trezor-firmware/.venv
. /home/wink/prgs/forks/trezor-firmware/.venv/bin/activate
wink@3900x 24-03-22T23:23:15.168Z:~/prgs/forks/trezor-firmware/core (main)
$ . /home/wink/prgs/forks/trezor-firmware/.venv/bin/activate
(trezor-firmware-py3.11) wink@3900x 24-03-22T23:23:15.179Z:~/prgs/forks/trezor-firmware/core (main)
$ rustc --version
rustc 1.79.0-nightly (1388d7a06 2024-03-20)
(trezor-firmware-py3.11) wink@3900x 24-03-22T23:23:50.263Z:~/prgs/forks/trezor-firmware/core (main)
$ gcc --version
gcc (GCC) 13.2.1 20230801
Copyright (C) 2023 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

(trezor-firmware-py3.11) wink@3900x 24-03-22T23:24:00.425Z:~/prgs/forks/trezor-firmware/core (main)
$ python --version
Python 3.11.8
(trezor-firmware-py3.11) wink@3900x 24-03-22T23:24:06.954Z:~/prgs/forks/trezor-firmware/core (main)
$ make JOBS=1 build_unix
./tools/build_templates
scons -Q -j 1 CFLAGS="-DSCM_REVISION='\"\x58\xc4\x80\xf1\xa6\x70\x31\x0b\x5d\x49\xe1\x96\x3c\x4b\x53\x98\x58\x10\x1a\xf7\"'" build/unix/trezor-emu-core  \
	TREZOR_MODEL="T" CMAKELISTS="0" \
	PYOPT="0" BITCOIN_ONLY="0" TREZOR_EMULATOR_ASAN="0"
python ../common/protob/pb2py /home/wink/prgs/forks/trezor-firmware/common/protob/messages-binance.proto ... --qstr-out build/unix/genhdr/qstrdefs.protobuf.h --bitcoin-only=0
gcc -E -DNO_QSTR -DN_X64 -DN_X86 -DN_THUMB -DSCM_REVISION='"\x58\xc4\x80\xf1\xa6\x70\x31\x0b\ ... -I/usr/include/webp vendor/micropython/extmod/vfs_posix_file.c > build/unix/vendor/micropython/extmod/vfs_posix_file.upydef
...
gcc -o build/unix/vendor/micropython/py/stackctrl.o -c -DSCM_REVISION='"\x58\xc4\x80\xf1\xa6\ ... -I/usr/include/webp vendor/micropython/py/stackctrl.c
vendor/micropython/py/stackctrl.c: In function ‘mp_stack_ctrl_init’:
vendor/micropython/py/stackctrl.c:32:32: error: storing the address of local variable ‘stack_dummy’ in ‘mp_state_ctx.thread.stack_top’ [-Werror=dangling-pointer=]
   32 |     MP_STATE_THREAD(stack_top) = (char *)&stack_dummy;
vendor/micropython/py/stackctrl.c:31:18: note: ‘stack_dummy’ declared here
   31 |     volatile int stack_dummy;
      |                  ^~~~~~~~~~~
In file included from vendor/micropython/py/runtime.h:29,
                 from vendor/micropython/py/stackctrl.c:27:
vendor/micropython/py/mpstate.h:323:23: note: ‘mp_state_ctx’ declared here
  323 | extern mp_state_ctx_t mp_state_ctx;
      |                       ^~~~~~~~~~~~
cc1: all warnings being treated as errors
scons: *** [build/unix/vendor/micropython/py/stackctrl.o] Error 1
make: *** [Makefile:266: build_unix] Error 2
(trezor-firmware-py3.11) wink@3900x 24-03-22T23:25:00.405Z:~/prgs/forks/trezor-firmware/core (main)
$ 
```
**Expected behavior**
I expect the compile to complete without error using the latest tools.

**Screenshots**

**Additional context**

**Comment by winksaville** [comment] 2024-03-22 23:49
I'd like to suggest the solution is to upgrade `micropython` from v1.19.1 to [v1.22.2](https://github.com/micropython/micropython/releases/tag/v1.22.2).

**Comment by prusnak** [comment] 2024-03-23 00:26
While I am not saying we should not bump the micropython version, the correct way how to build Trezor firmware in a reproducible way is to use Docker via `./build-docker.sh` script.

**Comment by prusnak** [comment] 2024-03-23 00:28
Closing as duplicate of https://github.com/trezor/trezor-firmware/issues/2990

**Closed by prusnak** 2024-03-23 00:28 UTC
Labels: bug

**Comment by CashewTTS** [comment] 2024-05-12 02:11
In the meantime, I'm working around the issues by just adding this line to core/Makefile:
```CFLAGS += -Wno-dangling-pointer -Wno-error=enum-int-mismatch```

**Comment by mullroy** [comment] 2024-05-18 13:40
> In the meantime, I'm working around the issues by just adding this line to core/Makefile: `CFLAGS += -Wno-dangling-pointer -Wno-error=enum-int-mismatch`

It appears that the CFLAGS are used by GCC, but not when Python is parsing the project files, still causing a build failure. 
My system, using the package versions bundled with the distribution:
&nbsp;&nbsp;Ubuntu 24.04 LTS
&nbsp;&nbsp;GCC & arm-none-eabi-gcc version 13.2.0
&nbsp;&nbsp;Python 3.12.3
Installed rustup separately:
apt-get install rustup
rustup install nightly-2023-04-16
&nbsp;&nbsp;Rust 1.71.0-nightly
 
I've managed to build_firmware & build_unix by embedding the override directly in the source file, as follow:

vendor/micropython/mpy-cross/main.c:
Line 333:Change int to mp_import_stat_t
&nbsp;&nbsp;&nbsp;mp_import_stat_t mp_import_stat(const char *path) {
&nbsp;&nbsp;&nbsp;(void)path;
&nbsp;&nbsp;&nbsp;return MP_IMPORT_STAT_NO_EXIST;
}

vendor/micropython/py/stackctrl.c:
void mp_stack_ctrl_init(void) {
&nbsp;&nbsp;&nbsp;volatile int stack_dummy;
&nbsp;&nbsp;&nbsp;#pragma GCC diagnostic push
&nbsp;&nbsp;&nbsp;#pragma GCC diagnostic ignored "-Wdangling-pointer"
&nbsp;&nbsp;&nbsp;MP_STATE_THREAD(stack_top) = (char *)&stack_dummy;
&nbsp;&nbsp;&nbsp;#pragma GCC diagnostic pop
}

Rust::Bindgen also needed to be updated:
core/embed/rust/Cargo.toml:
[build-dependencies.bindgen]
version = "0.69.4"
Inside the core/embed/rust directory, run: 'cargo update'
