### ISSUE TITLE
Cardano (ADA) transaction often fails when using 2.3.0

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-firmware#998] opened 2020-05-15 12:01 UTC
**Describe the bug**
Cardano (ADA) broken in latest 2.3.0 FW

**Firmware version or revision**
2.1.8 - works fine
2.3.0 - sometimes failed
public revisions
wallet uses connect v8

**Desktop/smartphone setup (please complete the following information):**
latest nixos and chrome

**To Reproduce**
go to https://adalite.io/
send transaction
strange is that it asks for passphrase twice to open wallet
sometimes it ends with: Transaction Rejected By Network: Submitting the transaction into Cardano network failed.

**Expected behavior**
you can send transaction

**Comment by tsusanka** [comment] 2020-05-15 12:17
@bosomt could you send me some ADA to `Ae2tdPwUPEYvtL72TZSjCza9corzRq8YDu9JPihLkcSi5tTcTTf7cgZw21m`?

**Comment by bosomt** [comment] 2020-05-15 12:20
@tsusanka Transaction submitted

**Comment by bosomt** [comment] 2020-05-18 14:17
@tsusanka 

new info from customer:

If I try to send all my funds (a **big amount of UTXO's**), I get the situation described in the ticket;

If I try to send an amount that requires **less UTXO's** (but more then one), the Trezor gets a **black screen** and adalite.io stucks waiting for the signed transaction;

If I send an amount that requires only **one UTXO** I can **successfully** send the transaction.

**Comment by tsusanka** [comment] 2020-05-18 15:24
@bosomt can you try transaction with two UTXOs then?

Also, the customer is using 2.3.0, correct?

**Comment by bosomt** [comment] 2020-05-19 05:30
@tsusanka i will send you PM to arrange that ransaction

and yes user configuration is **Model - Trezor T, FW 2.3.0 Browser: Chrome 81.0.4044.138 OS: OS X 10.14.6 64-bit
**

**Comment by refi93** [comment] 2020-05-19 14:08
@bosomt @tsusanka Adalite dev here and we looked at the issues reported here:

1. duplicate passphrase prompt

we looked into the duplicate passphrase prompt and it turns out that likely a change between fw version 2.2.0 and 2.3.0 that disabled caching of the passphrase resulted in this behavior. The problem seems to be that one "cardanoGetPublicKey" instruction to trezor-connect gets translated into a "GetAddress" and "GetCardanoPublicKey" message to trezor and since cardano uses a different seed than the generic "GetAddress" instruction, it generates the seed from scratch in "CardanoGetPublicKey", prompting the user for the passphrase again. The question is - why trezor-connect initiates a GetAddress message in the first place - is that some kind of "preflight" message?

Attaching a dump from the trezor emulator while sending a single "cardanoGetPublicKey" message via trezor-connect js API:

https://pastebin.com/abB8gUnX

get_keychain function used for GetAddress message:
https://github.com/trezor/trezor-firmware/blob/core/v2.2.0/core/src/apps/common/seed.py#L112

get_keychain function used for GetCardanoPublicKey message:
https://github.com/trezor/trezor-firmware/blob/core/v2.2.0/core/src/apps/cardano/seed.py#L42

looking at the history of those files you can see that passphrase was previously cached, so this was not an issue previously.

2. tx submission failure with "Transaction rejected by Network"

Regarding the problems with submission failing with "Transaction Rejected By Network: Submitting the transaction into Cardano network failed." message, this imho is not related to Trezor and it may have been related to transient network issues on Adalite's side which spiked around May 1st to May 6th (if that's when the customer reported it) and we managed to reduce them but we are still looking into the root cause: https://github.com/Emurgo/cardano-http-bridge/issues/17 - it seems as the cardano blockchain node(s) we communicated with hanged intermittently which is beyond our control. Does that network error persist?

3. Txs with many utxos fail:

Lastly, regarding the failure of transactions with many utxos, this is likely related to this issue: https://github.com/trezor/trezor-firmware/issues/94 - back in the day we managed to partially optimize the memory usage but the root problem is still there (tx serialization seems to take too much space and also the tx input verification is suboptimal in terms of memory usage) and the best available workaround as of now, unfortunately, is to send smaller transactions with less utxos - fortunately, this is to be fixed in the upcoming shelley update of the cardano blockchain which introduces significant changes in the transaction format and this piece will be reimplemented from scratch: https://github.com/trezor/trezor-firmware/issues/948

**Comment by bosomt** [comment] 2020-05-20 07:55
i just sent 10 transactions between 2.3.0deviceswith more inputs like this: https://seiza.com/blockchain/transaction/7c8755f90a4b2fa9f020a41f9dde25cee743ddf19c34557dcbdbc94139070fdb

and it works fine
@tsusanka close ?

**Comment by tsusanka** [comment] 2020-05-23 11:26
@refi93 thanks for the report!

-----

> 1. duplicate passphrase prompt

> we looked into the duplicate passphrase prompt and it turns out that likely a change between fw version 2.2.0 and 2.3.0 that disabled caching of the passphrase resulted in this behavior.

We have changed how passphrase works in 2.3.0. More info [in the docs](https://docs.trezor.io/trezor-firmware/common/communication/passphrase-redesign-migration.html).

However, Connect solves this for you, so this should not require any work from you.

> The question is - why trezor-connect sends an additional GetAddress message if from js only "CardanoGetPublicKey" is being sent - is that some kind of "preflight" message? Is there a way to skip it?

Yes something like "preflight" message. Connect uses that to verify that user entered the same passphrase as before. We have not realized completely this will cause the duplication for Cardano.

There is currently no way to skip this. I will open an issue in Connect repo to tackle this. [todo: link the issue]

----

> 2. tx submission failure with "Transaction rejected by Network"
> Did that network error happen even more recently?

Not that I know of! Ok, so I take it as not related to us.

---

> 3. Txs with many utxos fail

Ok, thanks for the info!

**Comment by tsusanka** [comment] 2020-05-23 11:33
Also @matejcik had a good point we can improve this for Shamir users - #1007.

**Comment by tsusanka** [comment] 2020-05-25 11:31
@refi93 since this is more of a Connect issue, I am closing this one. Let me know if I have missed something.

**Closed by tsusanka** 2020-05-25 11:31 UTC
Labels: P4 Low, S4 Low, W?, altcoin, bug
