### ISSUE TITLE
Support TRON(TRX) on Trezor

### ISSUE THREAD

**Issue by ferdinand026** [trezor/trezor-firmware#4169] opened 2024-09-10 13:26 UTC
TRON (TRX) is one of the top 10 cryptocurrency according to [Coinmarketcap](https://coinmarketcap.com/) and the TRON community has been thriving over the years. It has a huge number of users. Having a secure hardware wallet storage device is imperative for all users. so It'd be a good news if Trezor supports TRX.

Describe the solution you'd like
Whatever allows TRX to be stored and transferred from a Trezor One / Trezor T .

Describe alternatives you've considered
[Ledger Wallet](https://support.ledger.com/article/360006904193-zd)

Additional context
https://tron.network/

**Comment by matejcik** [comment] 2024-09-10 13:39
duplicate of #1532

**Closed by matejcik** 2024-09-10 13:39 UTC
